### ISSUE TITLE
.wav Downloading

### ISSUE THREAD

**Issue by cpbridges** [deckbsd/glouton-satnogs-data-downloader#1]
Hi there! Interesting project!
What would be the command line required to only download the .wav files for a given NORAD ID?
Can you also list the dependancies please?
73s Chris

**Comment by deckbsd** [comment]
Hello @cpbridges ,

Thanks for your concern and remarks.

Actually there are no .wav files i think, satnogs is using .ogg file format which has the name "payload" in the system. So if you want to download this file for the norad id 25338 you have to enter the command (you have to enter a start date and an end date) : "python ./glouton.py -s 2017-05-20T00:51:54 -e 2017-09-20T00:51:54 -n 25338 --payload" . When you are talking about dependencies, are you talking about the python ones ? if yes, all are in the requirements.txt file and you can install it with the command line : "pip install -r requirements.txt" :-)

I hope i answered correctly to your issue.

73s

**Comment by jtippman** [comment]
I believe you have to change "payload" in payloadDownloadCommand.py to "archive_url" to now download the .ogg file.

**Comment by deckbsd** [comment]
Correct, apparently they changed that. I'm going to fix it.

Thanks for the hint

**Comment by deckbsd** [comment]
I made a quick fix, so it's ok now :)

I will properly refactor the code now.
